FROM node:20

RUN npm ci --legacy-peer-deps --fetch-retries=5 --fetch-retry-mintimeout=10000

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci --legacy-peer-deps

COPY . .
RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "dev"]